version: '3'
services:
  service_y:
    build:
      context: './service_y/'
    volumes:
      - './service_y:/service'
    ports:
      - '8080:8080'

  service_x:
    build:
      context: './service_x/'
    volumes:
      - './service_x:/service'
    ports:
      - '8081:8081'

  kafka:
    image: spotify/kafka
    ports:
      - '9092:9092'
      - '7203:7203'
    extra_hosts:
      - 'kafka:172.19.0.2'
    environment:
      - ADVERTISED_HOST=kafka
      - ADVERTISED_PORT=9092
