version: '3'
services:
  service_y:
    build:
      context: './service_y/'
    volumes:
      - './service_y:/service'
    ports:
      - '8080:8080'

  service_x:
    build:
      context: './service_x/'
    volumes:
      - './service_x:/service'
    ports:
      - '8081:8081'

  zookeeper:
    image: zookeeper:3.4
    ports:
      - '2181:2181'

  kafka:
    image: ches/kafka:latest
    ports:
      - '9092:9092'
      - '7203:7203'
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - ZOOKEEPER_IP=zookeeper
    volumes:
      - './kafka_data:/data'
      - './kafka_logs:/logs'

